### ISSUE TITLE
Could not get zfunctions to load

### ISSUE THREAD

**Issue by kohane27** [mattmc3/zfunctions#2]
Hello there. Hope you're doing well.

I'm trying to get `zfunctions` to work but failed to do so.

1. I have the following line in `~/.zshrc`:

```bash
export ZFUNCDIR=$HOME/.config/zsh/functions
```

2. I have the following lines in `~/.zsh_plugins.txt` (I'm using `antidote`):

```
mattmc3/zephyr path:plugins/directory
mattmc3/zephyr path:plugins/editor
mattmc3/zephyr path:plugins/history
mattmc3/zephyr path:plugins/completion
```

According to https://github.com/mattmc3/zephyr/tree/main#plugins , `zfunctions` is included.

3. Launch a new shell and test with:

```bash
(( $+functions[autoload-dir] )) && echo "zfunctions loaded" || echo "zfunctions not loaded"
```

and got

```
zfunctions not loaded
```

Any input is much appreciated. Thank you again.

**Comment by mattmc3** [comment]
Good catch - this was a problem with the readme. The code you want is:

```zsh
(( $+functions[funcsave] )) && echo "zfunctions loaded" || echo "zfunctions not loaded"
```

I pushed a fix.

**Comment by mattmc3** [comment]
You'll also need to add this to your .zsh_plugins.txt

```
mattmc3/zephyr path:plugins/zfunctions
```

**Comment by kohane27** [comment]
Ohhh I get it now.

Given [Plugins](https://github.com/mattmc3/zephyr/tree/main#plugins), the user can pick and choose which plugins to load.

It makes sense as I'm on Linux and so `homebrew` and `macos` would not apply for my use case. 

After adding the line `mattmc3/zephyr path:plugins/zfunctions`, the command `(( $+functions[funcsave] )) && echo "zfunctions loaded" || echo "zfunctions not loaded"` works! Thank you!
